name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig (nightly)
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - name: Build
        run: zig build

      - name: Performance smoke test (localhost 80-555, c=100, timeout=200ms, <10s)
        run: |
          start=$(date +%s%3N)
          ./zig-out/bin/zigscan -t 127.0.0.1 -r 80-555 -c 100 --timeout 200 >/dev/null
          end=$(date +%s%3N)
          dur=$((end-start))
          echo "duration=${dur}ms"
          if [ "$dur" -gt 10000 ]; then
            echo "FAIL: scan took >10s"
            exit 1
          fi

      - name: Run help test
        run: ./zig-out/bin/zigscan --help
        if: runner.os != 'Windows'
        
      - name: Run help test (Windows)
        run: ./zig-out/bin/zigscan.exe --help
        if: runner.os == 'Windows'

  lint:
    name: Format Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig (nightly)
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - name: Check formatting
        run: zig fmt --check src/
